version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: fitlogr
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
volumes:
  mongodb_data: