import './globals.css'

import { Inter, Roboto_Flex as RobotoFlex } from 'next/font/google'
import React from 'react'

import { cn } from '@/lib/utils'

import { NextAuthProvider } from './providers'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

const roboto = RobotoFlex({
  subsets: ['latin'],
  variable: '--font-heading'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable,
          roboto.variable
        )}
      // className={'min-h-screen ' + inter.className}
      >
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
